#######################################################################
# WARNING: This file automatically generated by Borg on <%=Date.create().format('{yyyy}-{MM}-{dd} {HH}:{mm}:{ss} {tz}')%>
#          If you need to edit this file, do so in the Borg repository.
#          Any change you make here WILL be overridden on assimilation.
#######################################################################

biff = no
append_dot_mydomain = no
smtpd_use_tls = <%= @server['postfix']['smtpd_use_tls'] %>
<% if @server['postfix']['smtpd_use_tls'] == "yes": %>
smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache
<% end %>
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache
smtp_sasl_auth_enable = <%= @server['postfix']['smtp_sasl_auth_enable'] %>
<% if @server['postfix']['smtp_sasl_auth_enable'] == "yes": %>
smtp_sasl_password_maps = <%= @server['postfix']['smtp_sasl_password_maps'] %>
smtp_sasl_security_options = <%= @server['postfix']['smtp_sasl_security_options'] %>
smtp_tls_CAfile = <%= @server['postfix']['smtp_tls_cafile'] %>
smtp_use_tls = <%= @server['postfix']['smtp_use_tls'] %>
<% end %>
myhostname = <%= @server['postfix']['myhostname'] %>
<% if @server['postfix']['mydomain']: %>
mydomain = <%= @server['postfix']['mydomain'] %>
<% end %>
myorigin = <%= @server['postfix']['myorigin'] %>
smtpd_banner = $myhostname ESMTP $mail_name
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydestination = <%= @server['postfix']['myhostname'] %>, <%= @server['hostname'] %>, localhost.localdomain, localhost
<% if @server['postfix']['mail_type'] == "master": %>
relayhost =
mynetworks = <%= @server['postfix']['mail_relay_networks'] %>
inet_interfaces = <%= @server['postfix']['inet_interfaces'] || 'all' %>
<% else: %>
relayhost = <%= @server['postfix']['relayhost'] %>
mynetworks = <%= @server['postfix']['mail_relay_networks'] %>
inet_interfaces = <%= @server['postfix']['inet_interfaces'] || 'loopback-only' %>
<% end %>
<% if @server['postfix']['use_procmail']: %>
mailbox_command = /usr/bin/procmail -a "$EXTENSION"
<% end %>
mailbox_size_limit = 0
recipient_delimiter = +

milter_default_action = <%= @server['postfix']['milter_default_action'] %>
milter_protocol = <%= @server['postfix']['milter_protocol'] %>
smtpd_milters = <%= @server['postfix']['smtpd_milters'] %>
non_smtpd_milters = <%= @server['postfix']['non_smtpd_milters'] %>

<% if @server['postfix']['sender_canonical_classes']: %>
sender_canonical_classes = <%= @server['postfix']['sender_canonical_classes'] %>
<% end %>
<% if @server['postfix']['recipient_canonical_classes']: %>
recipient_canonical_classes = <%= @server['postfix']['recipient_canonical_classes'] %>
<% end %>
<% if @server['postfix']['canonical_classes']: %>
canonical_classes = <%= @server['postfix']['canonical_classes'] %>
<% end %>
<% if @server['postfix']['sender_canonical_maps']: %>
sender_canonical_maps = <%= @server['postfix']['sender_canonical_maps'] %>
<% end %>
<% if @server['postfix']['recipient_canonical_maps']: %>
recipient_canonical_maps = <%= @server['postfix']['recipient_canonical_maps'] %>
<% end %>
<% if @server['postfix']['canonical_maps']: %>
canonical_maps = <%= @server['postfix']['canonical_maps'] %>
<% end %>
<% if @server['postfix']['transport_maps'] && @server['postfix']['transport']: %>
transport_maps = <%= @server['postfix']['transport_maps'] %>
<% end %>
